# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
-   repo: https://github.com/executablebooks/mdformat/
    rev: 0.7.11
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-black
        - mdformat_tables
